markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title.html
name: "杂草丛"
markdown: rdiscount

author: "hhuai"
atom-baseurl: "http://blog.huahua8.cn"
disqus: "hhuai"

safe: false
cdn_url: 'http://hhuaiblog.qiniudn.com'

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Blogroll
    class: fa fa-link
    href: /links.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

